# Development Dependencies
#
# It contains dependencies to run tests and linting
# It should be installed along the normal dependencies in environment.yml
channels:
  - conda-forge

dependencies:
  - mypy == 0.770
  - flake8 == 3.8.2
  - pytest == 5.4.3
  - pydocstyle == 5.0.2
  - black == 19.10b0
