channels:
  - pytorch
  - plotly
  - conda-forge
  - anaconda

dependencies:
  - python >=3.7
  - pytorch ==1.6
  - torchvision ==0.7.0
  - cudatoolkit =10.1
  - plotly >=4.8
  - plotly-orca >=1.3
  - matplotlib
  - numpy
  - pandas
  - pyyaml
  - pip
  - pip:
    - injector
    - kornia
