dataset:
  source: mini_image_net
dataloader:
  batch_size: 128
scheduler:
  train:
    multistep:
      milestones: [50, 65, 80]
trainer:
  epochs: 100
  support_training:
    max_epochs: 300
optimizer:
  train:
    learning_rate: 0.05
evaluation:
  num_iterations: 250
transform:
  image_size: [84, 84]
  crop_size: [84, 84]
  crop_padding: 8
